"""initial_schema

Revision ID: b68bcc5d992e
Revises:
Create Date: 2026-01-31 01:22:23.261482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b68bcc5d992e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "roadmaps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "COMPLETED", name="roadmapstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roadmaps_status"), "roadmaps", ["status"], unique=False)
    _ = op.create_table(
        "phases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("roadmap_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order_num", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "COMPLETED", name="lessonstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["roadmap_id"],
            ["roadmaps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phases_roadmap_id"), "phases", ["roadmap_id"], unique=False)
    op.create_index(op.f("ix_phases_status"), "phases", ["status"], unique=False)
    _ = op.create_table(
        "lessons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("phase_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("order_num", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "COMPLETED", name="lessonstatus"),
            nullable=False,
        ),
        sa.Column("time_spent", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_phase_id"), "lessons", ["phase_id"], unique=False)
    op.create_index(op.f("ix_lessons_status"), "lessons", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lessons_status"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_phase_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_phases_status"), table_name="phases")
    op.drop_index(op.f("ix_phases_roadmap_id"), table_name="phases")
    op.drop_table("phases")
    op.drop_index(op.f("ix_roadmaps_status"), table_name="roadmaps")
    op.drop_table("roadmaps")
    # ### end Alembic commands ###
