"""Add code review models

Revision ID: cc1cb51cd170
Revises: b68bcc5d992e
Create Date: 2026-02-01 15:46:55.847413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc1cb51cd170"
down_revision: str | Sequence[str] | None = "b68bcc5d992e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_reviews",  # pyright: ignore[reportUnusedCallResult]
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lesson_id", sa.String(), nullable=False),
        sa.Column("code_content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="codereviewstatus"),
            nullable=False,
        ),  # noqa: E501
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_reviews_lesson_id"), "code_reviews", ["lesson_id"], unique=False)
    op.create_index(op.f("ix_code_reviews_status"), "code_reviews", ["status"], unique=False)
    op.create_table(
        "code_review_findings",  # pyright: ignore[reportUnusedCallResult]
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("review_id", sa.String(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("socratic_question", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["code_reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_review_findings_review_id"),
        "code_review_findings",
        ["review_id"],
        unique=False,
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_code_review_findings_review_id"), table_name="code_review_findings")
    op.drop_table("code_review_findings")
    op.drop_index(op.f("ix_code_reviews_status"), table_name="code_reviews")
    op.drop_index(op.f("ix_code_reviews_lesson_id"), table_name="code_reviews")
    op.drop_table("code_reviews")
    # ### end Alembic commands ###
